### ISSUE TITLE
Handle errors in the queue

### ISSUE THREAD

**Issue by Drugoy** [sgratzl/slack-cleaner#29]
Hello.
Whenever I `--perform` some query that is to delete tens of messages - I usually get 429 errors (about exceeding rate limit).
If I set `--rate` high enough to not get those errors - deleting goes too slow: even with rate of 0.7 I from time to time get those errors, so I'd rather go at rate 0.1 and delete things faster but also get more 429 errors.

Anyways, my question is about the exit status: shouldn't it be non-zero in case there was at least a single message not deleted due to an error?
I think it makes sense to set exit status equal the number of failed attempts to delete a message.

Or there should be an option to just move the failed tasks to the end of queue?

**Comment by Drugoy** [comment]
Also, I don't want to open a separate ticket, but I'm curious - is it even worth deleting messages after passing the free limit?
I can't access old messages, I thought deleting some of the ones I see would result into the same number of older message would become accessible to me, but I simply don't see it.
Or does slack re-calculates the limits periodically (not instantly)?

**Comment by sgratzl** [comment]
re limit: as far as I know it calculates the current stats every other day or so. At least when I delete a bunch of messages it takes up to two days till I see it in the summary visualization. 

re rate: as the API states it rates the number of delete operations with around 100 per minute. So 0.7 may work but not always due to some timing issues. 

re requeue and everything: take a look at the https://github.com/sgratzl/slack-cleaner/tree/develop branch. It is a rewrite of the whole module focusing on being used as a python module and not as a command line tool (tool a wrapper exists). Thus you can easily implement your own logic with a couple of lines of code.

**Comment by Drugoy** [comment]
Thanks, got it.
