### ISSUE TITLE
Channel, direct message or private group not found

### ISSUE THREAD

**Issue by paragbaxi** [sgratzl/slack-cleaner#72]
**Describe the bug**
Tried to delete from DM but direct message not found.

**To Reproduce**
1. slack-cleaner --token "token" --message --direct "PERSON" --user "USER" --before 20200101
2. See error

**Expected behavior**
Messages before 2020 to PERSON from USER are deleted

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
Tried "Person Lastname", "PersonLastname", "Person" and even "ChannelIDofPersonDM".

**Comment by sgratzl** [comment]
have you tried `--info` to get a list of channels, groups, and users?

As an alternative I can recommend https://github.com/sgratzl/slack_cleaner2 which uses a more python approach thus easier to explore.

Note: it is not possible due to slack restrictions that you delete direct messages which were not written by yourself. Regardless of the role you have or scope you assign in the free version you cannot delete any messages in a direct chat that were not written by yourself.

**Comment by paragbaxi** [comment]
This fixed it.
