### ISSUE TITLE
--keeppinned unrecognized

### ISSUE THREAD

**Issue by jonfairbanks** [sgratzl/slack-cleaner#9]
When using the `--keeppinned` argument, I am seeing an unrecognized argument error. If I remove this argument, everything runs well. Was this option removed or renamed recently? 

Launch Command: 
`slack-cleaner --token TOKEN --message --keeppinned --channel test --user "*" --perform --rate 1`

Console Output:
`usage: slack-cleaner [-h] --token TOKEN [--log] [--rate RATE]
                     (--message | --file)
                     [--channel CHANNEL | --direct DIRECT | --group GROUP | --mpdirect MPDIRECT]
                     [--user USER] [--bot] [--after AFTER] [--before BEFORE]
                     [--types TYPES] [--perform]
slack-cleaner: error: unrecognized arguments: --keeppinned`

Per the Readme, this should be right:
`usage: slack-cleaner [-h] --token TOKEN [--log] [--quiet] [--rate RATE]
                     [--as_user] [--message | --file] [--regex]
                     [--channel CHANNEL] [--direct DIRECT] [--group GROUP]
                     [--mpdirect MPDIRECT] [--user USER] [--botname BOTNAME]
                     [--bot] **[--keeppinned]** [--after AFTER] [--before BEFORE]
                     [--types TYPES] [--pattern PATTERN] [--perform]`

**Comment by sgratzl** [comment]
you are using the old version, e.g. installed via `pip install slack-cleaner` (see https://github.com/kfei/slack-cleaner). Since, I'm not the owner of the pip package, I cannot update it to the latest version. 

please use the docker image or install the package using: `pip install -e git+https://github.com/sgratzl/slack-cleaner.git#egg=slack-cleaner`
